### ISSUE TITLE
Title should be translated

### ISSUE THREAD

**Issue by xbluemonkx** [nextcloud/welcome#19]
The title of the tile "Welcome" should be translated or configurable.

**Comment by 42ske** [comment]
Even better would be, if I could define the title and the shown emoji in the settings.

**Comment by eneiluj** [comment]
@xbluemonkx The title is translated but the app is not synced with any translation service for now. I'll probably do that soon.

@xbluemonkx @42ske The widget title is now configurable in theming settings.
It is not possible to configure the icon though. The Dashboard API on allows to set a CSS class for that.

v1.0.1 is out (requires NC >= 22).

**Comment by xbluemonkx** [comment]
Thanks! Installed it and it works!

**Comment by kyteinsky** [comment]
Closing since the issue has been resolved.
