### ISSUE TITLE
Markdown content file can't be in a GroupFolder

### ISSUE THREAD

**Issue by adamshand** [nextcloud/welcome#20]
Hey,

Thanks for the great plugin, very helpful for a project I've been working on.

As best as I can tell if you point the "Markdown content file" to a file within a GroupFolder it doesn't work.

I double checked permissions and there were no problems with the test user accessing the `welcome.md` we were using. 

It worked great if it wasn't in a GroupFolder but as soon as we pointed it to a copy of the file in a GroupFolder it stopped working.

NextCloud: 22.2.3 (official Docker image)
Welcome: 1.0.1
Group folders: 10.0.2

Thanks,
Adam.

**Comment by bastikus** [comment]
It works for me. NC 27.0.1 Groupfolders 15.0.1

**Comment by adamshand** [comment]
Will close this as fixed then. :-)
