### ISSUE TITLE
Text alignment 

### ISSUE THREAD

**Issue by bastikus** [nextcloud/welcome#39]
Is it possible to enable text alignment centered horizontally and vertically?

**Comment by kyteinsky** [comment]
This app does not handle the rendering of markdown. You'd have to take up with (https://github.com/nextcloud-libraries/nextcloud-vue) - component `NcRichText` takes care of that. The only way I know to center text in markdown is by using HTML, and `NcRichText` seems to ignore its existence altogether. Consider opening an issue there.
