### ISSUE TITLE
add do all existing users' dashboard

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/welcome#45]
Right now, the widget is added as default, but all existing users won't see it unless they add it themselves. I can see two things sysadmins might want:
* make this app 'mandatory', aka always shows up, can't remove it.
* click a button to add it to all dashboards - to use after the first installation of the app, for example. Users can then still decide to remove it of course.

**Comment by esenjin** [comment]
I agree, it would be very practical!

**Comment by kyteinsky** [comment]
this was merged earlier here as a button to enable the widget for all active users: #46
